[build-system]
requires = [
    "babel >= 2.8",
    "setuptools >= 42",
    "setuptools_scm[toml]>=3.4",
    "setuptools_scm_git_archive>=1.1",
    "wheel"
]
build-backend = "setuptools.build_meta"

[tool.setuptools_scm]
version_scheme = "release-branch-semver"
local_scheme = "dirty-tag"
